services:
  api:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    container_name: sentinel-api-prod
    restart: unless-stopped
    env_file:
      - ../../apps/api/.env.production
    environment:
      NODE_ENV: production
      PM2_MACHINE_NAME: sentinel-api
    ports:
      - "4000:4000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://api.sentinel.bbbsoftware.co.za
    container_name: sentinel-web-prod
    restart: unless-stopped
    env_file:
      - ../../apps/web/.env.production
    environment:
      NODE_ENV: production
      PM2_MACHINE_NAME: sentinel-web
    ports:
      - "3000:3000"
    depends_on:
      - api
